name: CI/CD

on:
  [push]

jobs:
  test:
    name: build
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Run tests
        run: go test -race ./...
      - name: Test
        run: go test -v ./...
